-- MySQL Script generated by MySQL Workbench
-- Wed May 29 01:37:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `comision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comision` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `comision` (
  `idComision` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idComision`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `comunidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comunidad` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `comunidad` (
  `idComunidad` INT NOT NULL AUTO_INCREMENT,
  `domicilio` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  `num_familias` INT NULL,
  `fecha_salida` DATE NULL,
  `vivienda` VARCHAR(45) NULL,
  `agua` VARCHAR(45) NULL,
  `excretas` VARCHAR(45) NULL,
  `comision_idComision` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idComunidad`, `comision_idComision`),
  CONSTRAINT `fk_comunidad_comision1`
    FOREIGN KEY (`comision_idComision`)
    REFERENCES `comision` (`idComision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `animales_domesticos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `animales_domesticos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `animales_domesticos` (
  `idAnimales_domesticos` INT NOT NULL,
  `mascotas` INT NULL,
  `para_consumo` INT NULL,
  `desparasitados` INT NULL,
  `comunidad_idComunidad` INT NOT NULL,
  PRIMARY KEY (`idAnimales_domesticos`, `comunidad_idComunidad`),
  CONSTRAINT `fk_animales_domesticos_comunidad1`
    FOREIGN KEY (`comunidad_idComunidad`)
    REFERENCES `comunidad` (`idComunidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `edades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edades` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `edades` (
  `idEdades` INT NOT NULL,
  `menor_1ano` INT NOT NULL,
  `ano1_a5` INT NOT NULL,
  `ano6_a14` INT NOT NULL,
  `ano15_a45_mas` INT NOT NULL,
  `ano15_a45_fem` INT NOT NULL,
  `mas_50` INT NOT NULL,
  `total` INT NULL,
  `comunidad_idComunidad` INT NOT NULL,
  PRIMARY KEY (`idEdades`, `comunidad_idComunidad`),
  CONSTRAINT `fk_edades_comunidad1`
    FOREIGN KEY (`comunidad_idComunidad`)
    REFERENCES `comunidad` (`idComunidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `embarazadas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `embarazadas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `embarazadas` (
  `idEmbarazadas` INT NOT NULL,
  `menor_17anos` INT NULL,
  `ano18_a21` INT NULL,
  `mayor_a21` INT NULL,
  `controles_prenatales_si` INT NULL,
  `controles_prenatales_no` INT NULL,
  `comunidad_idComunidad` INT NOT NULL,
  PRIMARY KEY (`idEmbarazadas`, `comunidad_idComunidad`),
  CONSTRAINT `fk_embarazadas_comunidad`
    FOREIGN KEY (`comunidad_idComunidad`)
    REFERENCES `comunidad` (`idComunidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `enfermedades_cronicas_nt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enfermedades_cronicas_nt` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `enfermedades_cronicas_nt` (
  `idEnfermedades_cronicas_NT` INT NOT NULL,
  `diabetes` INT NULL,
  `hipertension` INT NULL,
  `tabaquismo` INT NULL,
  `tuberculosis_tratado` INT NULL,
  `tuberculosis_notratado` INT NULL,
  `chagas` INT NULL,
  `comunidad_idComunidad` INT NOT NULL,
  PRIMARY KEY (`idEnfermedades_cronicas_NT`, `comunidad_idComunidad`),
  CONSTRAINT `fk_enfermedades_cronicas_nt_comunidad1`
    FOREIGN KEY (`comunidad_idComunidad`)
    REFERENCES `comunidad` (`idComunidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estudiantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estudiantes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `estudiantes` (
  `DNI` INT(11) NOT NULL,
  `apellido` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `comision_idComision` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DNI`, `comision_idComision`),
  CONSTRAINT `fk_estudiantes_comision1`
    FOREIGN KEY (`comision_idComision`)
    REFERENCES `comision` (`idComision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `trabajo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabajo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `trabajo` (
  `idTrabajo` INT NOT NULL,
  `Desempleado` INT NULL,
  `cta_propia_temporal` INT NULL,
  `cta_propia_permanente` INT NULL,
  `empleado` INT NULL,
  `ama_casa` INT NULL,
  `jubilado` INT NULL,
  `comunidad_idComunidad` INT NOT NULL,
  PRIMARY KEY (`idTrabajo`, `comunidad_idComunidad`),
  CONSTRAINT `fk_trabajo_comunidad1`
    FOREIGN KEY (`comunidad_idComunidad`)
    REFERENCES `comunidad` (`idComunidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id` INT(11) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `created` DATETIME NOT NULL,
  `last_login` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vacunas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vacunas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vacunas` (
  `idvacunas` INT NOT NULL,
  `completo` INT NULL,
  `incompleto` INT NULL,
  `comunidad_idComunidad` INT NOT NULL,
  PRIMARY KEY (`idvacunas`, `comunidad_idComunidad`),
  CONSTRAINT `fk_vacunas_comunidad1`
    FOREIGN KEY (`comunidad_idComunidad`)
    REFERENCES `comunidad` (`idComunidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cobertura_social`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cobertura_social` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cobertura_social` (
  `idcobertura_social` INT NOT NULL,
  `mutual_si` INT NULL,
  `mutual_no` INT NULL,
  `comunidad_idComunidad` INT NOT NULL,
  PRIMARY KEY (`idcobertura_social`, `comunidad_idComunidad`),
  CONSTRAINT `fk_cobertura_social_comunidad1`
    FOREIGN KEY (`comunidad_idComunidad`)
    REFERENCES `comunidad` (`idComunidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `nivel_educativo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nivel_educativo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `nivel_educativo` (
  `idnivel_educativo` INT NOT NULL,
  `primaria` INT NULL,
  `secundaria` INT NULL,
  `superior` INT NULL,
  `comunidad_idComunidad` INT NOT NULL,
  PRIMARY KEY (`idnivel_educativo`, `comunidad_idComunidad`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
